services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dating_database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  dating_app:
    build:
      context: ./app
    image: dating_app
    volumes:
      - ./photos:/photos
    restart: always
    depends_on:
      - postgres
    ports:
      - "7000:7000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/dating_database

  dating_frontend:
    build:
      context: ./frontend
    image: dating_frontend
    depends_on:
      - dating_app
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

volumes:
  pgdata:


