# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: app
    build: .
    command: gunicorn -b 0.0.0.0:5000 app.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/app.db
    volumes:
      - ./app:/code/app
      - ./db/:/db/
    ports:
      - "5000:5000"
